hugo-sid/hugo-blog-awesome

assets/sass/_layout.scss
Hi,
This small PR fixing the stretched image.
Solution:
Adding `object-fit: cover;` on `.author-avatar` class seems fix it.
Before adding `object-fit` class:
As you can see the image is stretched out.
After adding `object-fit` class:
The husky image size used above is : 900x500 pixel
=> fix: stretched image

layouts/partials/bio.html
Template error when params.author.avatar cannot be found.
Full error:
```
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1  
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template:   
index.html:8:15: executing "index.html" at <partial "bio" .>: error calling partial: "/home/mike/git/testblog  
/themes/hugo-blog-awesome/layouts/partials/bio.html:4:19": execute of template failed: template: partials/bio.html:4:19:   
executing "partials/bio.html" at <$image.Fill>: nil pointer evaluating resource.Resource.Fill  
Built in 17 ms
```
No
No, hope that's ok. It's quicker to make a PR than opening up an issue.
=> Fix template failure in bio.html when avatar cannot be found

exampleSite/config.toml, layouts/_default/single.html, layouts/partials/meta/post.html, layouts/partials/postCard.html
https://gohugo.io/functions/dateformat/
Dates are not formatted according the the language locale specified in config.toml. It sticks to English.
Sort of: now people can choose to display dates according to the language they want (`defaultContentLanguage` config).
Nope
- ~~It does, but I didn't find a way to format dates UK style, only US style 😕  (15 Feb 2022 vs. Feb 15, 2022)~~ fixed in config
=> Use dateFormat hugo function to support localization

layouts/404.html, layouts/partials/head.html, layouts/partials/postCard.html, layouts/partials/scriptsBodyEnd.html, layouts/partials/scriptsBodyStart.html
This issue exists when using hugo development server and remote device for testing. See screenshot bellow.
Website is loaded from remote IP like `10.0.0.194` but it's trying to load scripts from `localhost`. Same issue with link in `postCard` component.
No
No
=> Fix js loading and 404 page

README.md, exampleSite/config.toml, layouts/_default/single.html, layouts/partials/comments.html
Lack of support for a comments section at the bottom of posts.
Introduces a `comments.html` partial that is included at the bottom of `single.html` and defaults to using the builtin Disqus template if `.Site.DisqusShortname` is set.
Closes #32
=> feat: add comments partial

layouts/index.html
P : Fix for 404 errors in see all posts if the default URL is not root.  
S : Add a baseURL variable to the link in the button.  
no
[ Issue #36 (closed) ](https://github.com/hugo-sid/hugo-blog-awesome/issues/36)
=> Add baseURL variable on See all posts button

assets/js/theme.js
On Firefox, the theme toggle does not work for me, even on the example site. I believe this is because the event listeners are attached inside of a `setTimeout` call (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#deferral_of_timeouts_during_pageload)):
> Firefox will defer firing setTimeout() timers while the current tab is loading. Firing is deferred until the main thread is deemed idle (similar to [window.requestIdleCallback()](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)), or until the load event is fired.
The call to `window.addEventListener('DOMContentLoaded', ...)` therefore happens _after_ the DOM has already loaded, so the event is missed and the theme toggle event listeners are not attached.
This PR just removes the …
=> fix: resolve theme toggle race condition

exampleSite/config.toml
According to
https://gohugo.io/getting-started/configuration-markup/#table-of-contents, the "tableOfContents" section in the config file needs to be within the "markup" section, which I've tested and confirmed to be correct.
Config bug where tableOfContents is in the wrong section
=> Move tableOfContents sectin to correct part of config

exampleSite/content/pages/about.md, layouts/_default/single.html
Make specifying date optional. This is useful for standalone pages like about page.
https://github.com/hugo-sid/hugo-blog-awesome/discussions/78
=> fix: make specifying date optional

assets/sass/_miscellaneous.scss
fadein keyframe had value 0.8 instead of 1 for opacity 100%.
Opacity Issue
The Opacity was 0.8 instead of 1
No
Image 100% opacity
No
- [X ] I have verified that the code works as described/as intended.
- [X ] This change **does not** include any external library/resources.
- [ X] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [ X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
=> Update _miscellaneous.scss - fadein keyframe

layouts/index.html
should solve #50 
and allow to enforce default theme to dark by site developer in no-script browsers.
no
issue #50
=> Fix enforced defaultColor

layouts/partials/header.html
The header page titles (top right) are supposed to be bold when we are at that page. For example, "Posts" is supposed to be bold when we are in www.domain/posts, and it currently is not. A couple of typos are the cause.
No.
Not reported as far as I am concerned.
- [ x] I have verified that the code works as described/as intended.
- [ x] This change adds a social icon which has a permissive license to use it.
- [ x] This change **does not** include any external library/resources.
- [ x] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [ x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
=> Fixed bug for bold titles in header

exampleSite/config.toml, layouts/_default/rss.xml, netlify.toml
None.
Yes.  Adds support for full post content (instead of summary) in RSS feed.
Yes #109.
=> feat(RSS): add support for full post content in RSS feed

exampleSite/config.toml, layouts/partials/postCard.html
Fixes hugo error when `dateFormat` parameter is not set.
No.
https://github.com/hugo-sid/hugo-blog-awesome/issues/128
=> fix: hugo error when dateFormat parameter is not set

layouts/partials/header.html
Fix: Accesibility rules, regains 100% accesibility score, read more: https://dequeuniversity.com/rules/axe/4.7/select-name
Fixes the accessibility parameter on the `select` for language selector
Fixes the accessibility paramterer on the `select` for language selector, thus regaining 100% accessibility score on PagesInsight for desktop, follows the rules laid by: https://dequeuniversity.com/rules/axe/4.7/select-name and adds an `aria-label=""` so it doesn't add extra text on the page itself.
- [ x] I have verified that the code works as described/as intended.
- [x ] This change **does not** include any external library/resources.
- [ x] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [ x] I have enabled [maintainer edits for this …
=> Fix: Language Selector accessibility

.github/workflows/release.yml
Rename and regenerate the expiring GitHub action token.
No.
No.
=> ci: update GitHub access token for release please

exampleSite/config.toml, exampleSite/content/en/posts/table-of-content/index.md, layouts/_default/single.html
This PR addresses a requirement for my blog where I wanted to make the Table of Contents (ToC) visible to all users across all sections of each blog post. Currently, to achieve this, I had to override the `layouts/_default/single.html` file to open the ToC. This seemed like a functionality that could be supported by this template, so I've decided to try it.
As demonstrated in [this commit of my blog](https://github.com/cruizba/cruizba.dev/commit/7c3aa364cbc1f0283b781be14c4fb2d0474141c7), adding the `open` attribute to the `<details>` tag required overriding the entire HTML file.
This PR introduces a `tocOpen` parameter to control the visibility of the ToC. This new parameter doesn't alter any existing default configurations or behaviors. It simply provides an option to open the ToC either …
=> Add parameter to open ToC

assets/sass/_code.scss, exampleSite/content/en/posts/markdown-syntax/index.md
=> Fix: Inconsistent appearance of inline code, in lists, in light theme

.gitignore, README.md, exampleSite/hugo.toml, layouts/partials/comments.html, netlify.toml
Currently, when running hugo preview for the example site, a deprecation warning is emitted:
```
hugo --logLevel info --themesDir ../.. | grep deprecated
INFO  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
```
This PR fixes the deprecation warnings concerning the disqus comment system.
This PR also corrects the documentation for disqus comment system and for use of google analytics.
=> Fix disqus deprecation warning

exampleSite/content/de/posts/math-typesetting/index.md, exampleSite/content/en/posts/math-typesetting/index.md, exampleSite/content/it/posts/math-typesetting/index.md, exampleSite/content/ru/posts/math-typesetting/index.md, layouts/partials/helpers/katex.html
This PR bumps KaTeX scripts to their latest version.
It also changes name of config files in the KaTeX documentation from `config.toml` to `hugo.toml`.
=> Bump KaTeX to latest version 0.16.9

exampleSite/content/de/posts/rich-content/index.md, exampleSite/content/en/posts/rich-content/index.md, exampleSite/content/it/posts/rich-content/index.md, exampleSite/content/ru/posts/rich-content/index.md, layouts/partials/meta/post.html, netlify.toml
Pages of kind "page" don't allow the creation of a paginator (.Paginate or .Paginator) in the newest version of hugo.
Pages of kind "section" (e.g. /posts) still allow the creation. This fix adds a check for the kind of page and excludes pages with kind "page" from creating a paginator.
No
Closes #165
=> Fixes paginator issue since hugo v0.123.0

exampleSite/hugo.toml
Fixes broken RSS feed link on post pages.
No.
#160
=> fix: RSS link on post pages, closes #160

layouts/partials/meta/standard.html
If a page doesn't include its own banner/open graph image, this causes a fall-back to the site-wide image, reasoning that showing *something* is better than nothing.
Yes; as above.
No
=> feat: Use site image in absence of page image

layouts/partials/meta/post.html
When an `image:` attribute is added to a page's frontmatter, it breaks site building because the template syntax used to convert it to an absolute URL is incorrect. This is a fix for that.
No
No
=> fix: Incorrect syntax for post image URL

layouts/partials/meta/post.html
Running humanize on the name uses sentence case rather than title case, thus using lowercase for all words except the first. This way, the author can choose how they want their name to look.
1. Humanizing the author name is probably not the right behaviour since this will lowercase all but the first name.
2. This is the only reference I can see to an author *of a post* rather than of the site, so let's use the site author here too.
Sort of?
No
=> fix: Use author from site rather than post and don't humanize name

layouts/partials/head.html
Add Hugo's built-in support for generating social previews when posting a link on social media sites. (Uses the open graph protocol).
Problem: Social media previews are missing when posting a link from the site to social media such as Facebook. 
Solution: This PR adds hugo's built-in open graph protocol script.
Yes
https://github.com/hugo-sid/hugo-blog-awesome/discussions/215
=> Add Social Previews

archetypes/default.md, assets/sass/_listpage.scss, exampleSite/content/en/posts/markdown-syntax/index.md, layouts/partials/postCard.html
None.
Indeed.
This PR will add the option to starr single posts. An author can set the optional config `isStarred: true` in a posts front matter. This will cause a little star icon to be rendered (for the post) in the list of posts.
An author can use this to get a readers attention.
The mentioned star will only be shown in the list of posts - nowhere else (to not overload the theme).
**For the records**
I set the `isStarred: true` in the front matter of the _Markdown Syntax Guide_ en-us example post to showcase this new option.
It might be worth recreating the themes demo picture (used here: https://themes.gohugo.io/themes/hugo-blog-awesome/) to attract the attention of possible theme users. 🤓 
This feature was discussed here: https://github.com/hugo-sid/hugo-blog-awesome/discussions/222
=> Feat: starr posts to get readers attention

assets/sass/_code.scss
Fixed 'Long inline code does not break line' bug
If the inline code was long, the code would be unreadable on a small screen like a phone. 
no
Closes #133
=> fix: Change line when inline code is long

exampleSite/hugo.toml, layouts/_default/single.html
Add extra option to change the date format
displayed at the beginning of the single.html
The date format at the beginning of post did not follow the `dateFormat`
config option.
I added an extra option `postDateFormat` to set the date format at the beginning of a post.
I added this option because I like the idea of being able to display the date
more verbose at the start of the post. (Moreover this makes it possible
to add this in a backwards compatible manner, by not changing the current
behavior if the `postDateFormat` option is not defined)
See #177
=> fix: date on post is not following dateFormat 

README.md, layouts/partials/head.html
If theme user creates a "custom-head.html" partial, it will be included at the end of the <head> section.
Related discussion: https://github.com/hugo-sid/hugo-blog-awesome/discussions/152
=> feat: support user-supplied <head> html

README.md
Adds `chdir` command to two code blocks in the README.md in the Setup section
Setup is not copy and playable without changing in the correct folder before issuing the next command
Just documentation change, no code
Closes #247
=> docs: add missing chdir commands in Setup Section (#247)

exampleSite/content/fr/posts/markdown-syntax/index.md, exampleSite/hugo.toml, i18n/fr-fr.yaml
This PR improves the quality and accuracy of French translations in the Hugo Blog Awesome project. It corrects typos, adjusts grammar, and enhances the clarity of the Markdown guide and other translation-related content in the following files:
- `exampleSite/content/fr/posts/markdown-syntax/index.md`: Adjusted grammar and improved wording for the Markdown Syntax Guide.
- `exampleSite/hugo.toml`: Ensured French language settings are accurate and consistent.
- `i18n/fr-fr.yaml`: Fixed typos and refined wording for better translation accuracy.
No, this PR does not add a new feature. It focuses on refining the existing French translations.
No specific issue is linked to this PR.
=> fix: corrected French translations in Markdown guide and i18n file

layouts/partials/bio.html
Cleanup author image handling and use `<img />` `scrset` attribute to better expose display density-compliant images. Being the only image really showed in the entire theme, it deserves polish.
No
No
=> fix: align author image display size & actual size

layouts/partials/bio.html
Avatar images are currently cropped using `smart` mode, which in my experience leads to the avatar appearing off-centre. Changing to `center` fixes this.
No.
No.
=> fix: off-centre author avatars
