hugo-sid/hugo-blog-awesome

README.md, assets/js/goToTop.js, assets/sass/_dark.scss, assets/sass/_goToTop.scss, assets/sass/main.scss, exampleSite/config.toml, layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/scriptsBodyEnd.html, layouts/partials/svgs/arrowUp.svg
None
Yes. Add go to top button on blog posts.
https://github.com/hugo-sid/hugo-blog-awesome/discussions/29
=> feat: add go to top button

README.md
None. Update list of websites using this theme.
No
No
=> chore(README): add websites using this theme

README.md
None. This PR updates list of websites using this theme
No
No
=> Update list of websites using this theme

exampleSite/content/posts/rich-content/index.md
> WARN 2023/06/19 11:04:48 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "[...]/hugo-blog-awesome/exampleSite/content/posts/rich-content/index.md:22:1"
=> Fix deprecated Twitter post format

README.md
just adding my website to the readme
no
no
- [ x ] I have verified that the code works as described/as intended.
- [ x ] This change **does not** include any external library/resources.
- [ x ] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [ x ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
=> adding bskdany.com to the readme

README.md
None. Add contributors to readme.
No
No
=> chore: Update README.md - add contributors

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
None.
Yes. Adding support for Dev Containers.
No.
=> feat: add config for Dev containers

assets/sass/main.scss
https://github.com/hugo-sid/hugo-blog-awesome/issues/93#issue-1840107081
Yes.
https://github.com/hugo-sid/hugo-blog-awesome/issues/93
=> feat: include `_custom.scss` to facilitate quick and simple CSS adjustments #93

README.md
Changes the logo alt text.
No.
No.
=> chore: update logo alt text

README.md
Logo not displaying in readme.
No.
#106
=> Fix: logo not displaying in readme

README.md
=> Update README.md to add my website

exampleSite/content/posts/table-of-content/index.md, layouts/_default/single.html, layouts/partials/footer.html
Bug with disabling ToC on per post basis.
No.
#120
=> Fix ToC bug, update footer text

.github/workflows/stale.yml
Mark issues and PRs inactive for 21 days (instead of current setup - 7 days) as stale.
No.
No.
=> ci: update stale.yml GitHub action

assets/sass/_layout.scss, exampleSite/content/en/posts/math-typesetting/index.md
Fixes post title width on small screens.
No.
#136
=> fix: fix post title width on small screens closes #136

README.md
=> add my blog :-)

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md
- change Discussions to GitHub discussions
- add documentation for adding new language
No.
https://github.com/hugo-sid/hugo-blog-awesome/issues/142
=> chore: change Discussions to GitHub discussions

README.md
Adds my personal website (https://jmbhughes.com/) to the list of sites using this Hugo theme. 
Thanks for the theme! I love how minimal it is.
=> add jmbhughes

README.md
I'm absolutely loving this theme, looks fantastic and is highly functional. I did make a few tweaks to my instance though!
=> Add my website to the websites list

layouts/partials/meta/post.html
Brings post metadata in line with OpenGraph recommednations
Yes
No
=> Add og:url meta tag as per https://ogp.me/

.github/workflows/release.yml
Reverts hugo-sid/hugo-blog-awesome#205
=> Revert "chore(deps): update google-github-actions/release-please-action action to v4"

README.md
adding meanii.dev as using this theme section
=> add: meanii.dev as using this theme

README.md
=> added journeytolunar.com

layouts/partials/bio.html
SVG is not supported for avatar images, this fixes it
SVG support for avatar images
Nope
=> feat: svg support

README.md
=> added my personal site to readme

.devcontainer/devcontainer.json
Upgrades Node JS version to 20.
No
https://github.com/hugo-sid/hugo-blog-awesome/issues/260
=> chore: update devcontainer.json

README.md
add: blog.crisweb.com as using this theme
=> add: blog.crisweb.com as using this theme

README.md
- Adding my own site to the list.
- Also removing several sites that no longer use the theme.
=> add my site to the readme list + remove several that no longer use the theme

README.md
=> Added my blog to the wesbsite that uses this theme
